# This file is part of VertNet: https://github.com/VertNet/webapp
#
# VertNet is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# VertNet is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with VertNet.  If not, see: http://www.gnu.org/licenses

"""API module configuration file.
"""

import os
import sys

IS_DEV = os.environ.get('SERVER_SOFTWARE', '').startswith('Development')
sys.path.append(os.path.join(os.path.dirname(__file__), 'lib'))


# Set the namespace. If we're running in the devlopment environment, use
# 'dwcns' so that we can use the test data generated by dwc-indexer.
def namespace_manager_default_namespace_for_request():
    if IS_DEV:
        return 'dwcns'
    else:
        # DwC2013-style index
        # return 'index-2014-03-12'
        # DwC2015-style index:
        # index-2014-02-11a is an index with the dwc2015 schema indexing from
        # gulo with [org.gbif/dwca-reader "1.20-SNAPSHOT"] and
        # [dwca-reader-clj "0.10.1-SNAPSHOT"]
        return 'index-2014-02-11a'
